cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/thais/Downloads/pycairo-1.10.0/.waf3-1.6.4-e3c1e08604b18a10567cfcd2d02eb6e6/waflib/Tools/c_config.py", line 435, in run_c_code\n    bld.compile()\n  File "/home/thais/Downloads/pycairo-1.10.0/.waf3-1.6.4-e3c1e08604b18a10567cfcd2d02eb6e6/waflib/Build.py", line 192, in compile\n    raise Errors.BuildError(self.producer.error)\nwaflib.Errors.BuildError: Build failed\n -> task failed (exit status 1): \n\t{task 140021021206624: cprogram test.c.0.o -> testprog}\n[\'/usr/bin/gcc\', \'test.c.0.o\', \'-o\', \'/home/thais/Downloads/pycairo-1.10.0/build_directory/.conf_check_ccf711f63dc29532d96c942aada191bd/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib\', \'-lpython3.4\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\', \'-pthread\', \'-Wl,-O1\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\']\n'
